/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const compress: (a: number, b: number, c: number) => [number, number, number, number];
export const decompress: (a: number, b: number, c: number) => [number, number, number, number];
export const __wbg_compressionoptions_free: (a: number, b: number) => void;
export const compressionoptions_new: () => number;
export const compressionoptions_with_level: (a: number) => number;
export const compress_with_options: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const handle_file_upload: (a: any, b: number) => [number, number];
export const greet: (a: number, b: number) => void;
export const rust_zstd_wasm_shim_qsort: (a: number, b: number, c: number, d: number) => void;
export const rust_zstd_wasm_shim_malloc: (a: number) => number;
export const rust_zstd_wasm_shim_memcmp: (a: number, b: number, c: number) => number;
export const rust_zstd_wasm_shim_calloc: (a: number, b: number) => number;
export const rust_zstd_wasm_shim_free: (a: number) => void;
export const rust_zstd_wasm_shim_memcpy: (a: number, b: number, c: number) => number;
export const rust_zstd_wasm_shim_memmove: (a: number, b: number, c: number) => number;
export const rust_zstd_wasm_shim_memset: (a: number, b: number, c: number) => number;
export const rust_lz4_wasm_shim_malloc: (a: number) => number;
export const rust_lz4_wasm_shim_memcmp: (a: number, b: number, c: number) => number;
export const rust_lz4_wasm_shim_calloc: (a: number, b: number) => number;
export const rust_lz4_wasm_shim_free: (a: number) => void;
export const rust_lz4_wasm_shim_memcpy: (a: number, b: number, c: number) => number;
export const rust_lz4_wasm_shim_memmove: (a: number, b: number, c: number) => number;
export const rust_lz4_wasm_shim_memset: (a: number, b: number, c: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_2: WebAssembly.Table;
export const __wbindgen_export_3: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const closure21_externref_shim: (a: number, b: number, c: any) => void;
export const __wbindgen_start: () => void;
